Fix BPF selftests compilation failure in mainline due to change of bpf_d_path() signature
The error message is as follow

   progs/bpf_iter_task_vmas.c:52:14: error: passing 'const struct path *' to parameter of type 'struct path *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
     52 |                 bpf_d_path(&file->f_path, d_path_buf, D_PATH_BUF_SIZE);
        |                            ^~~~~~~~~~~~~
  1 error generated.

Signed-off-by: Shung-Hsi Yu <shung-hsi.yu@suse.com>