Revert "HACK: use my fork of libbpf/ci with the modification in get-linux-source"
This reverts commit ee40ce951376c6ace9be3f28021d7472498ceef2.

GitHub actions fails with

  Error: Missing download info for shunghsiyu/libbpf-ci@v3