Fix failure in sockmap_ktls
The follow tests are failing due to backport of upstream commit
5071a1e606b3 ("net: tls: explicitly disallow disconnect")

  Error: 211 sockmap_ktls
  Error: 211/1 sockmap_ktls/sockmap_ktls disconnect_after_delete IPv4 SOCKMAP
  Error: 211/3 sockmap_ktls/sockmap_ktls disconnect_after_delete IPv4 SOCKMAP
  Error: 211/5 sockmap_ktls/sockmap_ktls disconnect_after_delete IPv4 SOCKMAP
  Error: 211/7 sockmap_ktls/sockmap_ktls disconnect_after_delete IPv4 SOCKMAP

Backport commit 82303a059aab ("selftests/bpf: mitigate sockmap_ktls
disconnect_after_delete failure") to deal with that.

Signed-off-by: Shung-Hsi Yu <shung-hsi.yu@suse.com>