Fix BPF selftests compilation failure due to gettid() undefined
The compilation error is as follow:

  .../tools/testing/selftests/bpf/prog_tests/bpf_iter.c: In function 'test_task_common_nocheck':
  .../tools/testing/selftests/bpf/prog_tests/bpf_iter.c:231:26: error: implicit declaration of function 'gettid'; did you mean 'getgid'? [-Werror=implicit-function-declaration]
      231 |         skel->bss->tid = gettid();
          |                          ^~~~~~
          |                          getgid

Signed-off-by: Shung-Hsi Yu <shung-hsi.yu@suse.com>