Fix BPF selftests compilation failure on SLE15-SP{6,7} in ns_current_pid_tgid.c
The pid variable is of different type, thus causing compilation to fail
with the following error

/home/runner/work/libbpf/libbpf/.kernel/tools/testing/selftests/bpf/prog_tests/ns_current_pid_tgid.c: In function ‘test_current_pid_tgid’:
  /home/runner/work/libbpf/libbpf/.kernel/tools/testing/selftests/bpf/prog_tests/ns_current_pid_tgid.c:31:9: error: invalid type argument of unary ‘*’ (have ‘pid_t’ {aka ‘int’})
     31 |         *pid = sys_gettid();
        |         ^~~~

Signed-off-by: Shung-Hsi Yu <shung-hsi.yu@suse.com>