Fix BPF selftests compilation error in SLE15-SP{6,7} due to create_pair() and bpf_program__attach_sockmap().
Currently the BPF selftests fails to build with

  /home/runner/work/libbpf/libbpf/.kernel/tools/testing/selftests/bpf/prog_tests/sockmap_basic.c: In function ‘test_sockmap_vsock_delete_on_close’:
    TEST-OBJ [test_progs] sockopt_qos_to_cc.test.o
  /home/runner/work/libbpf/libbpf/.kernel/tools/testing/selftests/bpf/prog_tests/sockmap_basic.c:120:50: error: passing argument 3 of ‘create_pair’ makes integer from pointer without a cast [-Werror=int-conversion]
    120 |         err = create_pair(AF_VSOCK, SOCK_STREAM, &c, &p);
        |                                                  ^~
        |                                                  |
        |                                                  int *
  In file included from /home/runner/work/libbpf/libbpf/.kernel/tools/testing/selftests/bpf/prog_tests/sockmap_basic.c:17:
  /home/runner/work/libbpf/libbpf/.kernel/tools/testing/selftests/bpf/prog_tests/sockmap_helpers.h:315:54: note: expected ‘int’ but argument is of type ‘int *’
    315 | static inline int create_pair(int s, int family, int sotype, int *c, int *p)
        |                                                  ~~~~^~~~~~
  /home/runner/work/libbpf/libbpf/.kernel/tools/testing/selftests/bpf/prog_tests/sockmap_basic.c:120:15: error: too few arguments to function ‘create_pair’
    120 |         err = create_pair(AF_VSOCK, SOCK_STREAM, &c, &p);
        |               ^~~~~~~~~~~
  /home/runner/work/libbpf/libbpf/.kernel/tools/testing/selftests/bpf/prog_tests/sockmap_helpers.h:315:19: note: declared here
    315 | static inline int create_pair(int s, int family, int sotype, int *c, int *p)
        |                   ^~~~~~~~~~~
  /home/runner/work/libbpf/libbpf/.kernel/tools/testing/selftests/bpf/prog_tests/sockmap_basic.c:130:50: error: passing argument 3 of ‘create_pair’ makes integer from pointer without a cast [-Werror=int-conversion]
    130 |         err = create_pair(AF_VSOCK, SOCK_STREAM, &c, &p);
        |                                                  ^~
        |                                                  |
        |                                                  int *
  /home/runner/work/libbpf/libbpf/.kernel/tools/testing/selftests/bpf/prog_tests/sockmap_helpers.h:315:54: note: expected ‘int’ but argument is of type ‘int *’
    315 | static inline int create_pair(int s, int family, int sotype, int *c, int *p)
        |                                                  ~~~~^~~~~~
  /home/runner/work/libbpf/libbpf/.kernel/tools/testing/selftests/bpf/prog_tests/sockmap_basic.c:130:15: error: too few arguments to function ‘create_pair’
    130 |         err = create_pair(AF_VSOCK, SOCK_STREAM, &c, &p);
        |               ^~~~~~~~~~~
  /home/runner/work/libbpf/libbpf/.kernel/tools/testing/selftests/bpf/prog_tests/sockmap_helpers.h:315:19: note: declared here
    315 | static inline int create_pair(int s, int family, int sotype, int *c, int *p)
        |                   ^~~~~~~~~~~
  /home/runner/work/libbpf/libbpf/.kernel/tools/testing/selftests/bpf/prog_tests/sockmap_basic.c: In function ‘test_sockmap_skb_verdict_vsock_poll’:
    TEST-OBJ [test_progs] sockopt_sk.test.o
  /home/runner/work/libbpf/libbpf/.kernel/tools/testing/selftests/bpf/prog_tests/sockmap_basic.c:604:48: error: passing argument 3 of ‘create_pair’ makes integer from pointer without a cast [-Werror=int-conversion]
    604 |         if (create_pair(AF_VSOCK, SOCK_STREAM, &conn, &peer))
    TEST-OBJ [test_progs] spin_lock.test.o
        |                                                ^~~~~
        |                                                |
        |                                                int *
  /home/runner/work/libbpf/libbpf/.kernel/tools/testing/selftests/bpf/prog_tests/sockmap_helpers.h:315:54: note: expected ‘int’ but argument is of type ‘int *’
    315 | static inline int create_pair(int s, int family, int sotype, int *c, int *p)
        |                                                  ~~~~^~~~~~
  /home/runner/work/libbpf/libbpf/.kernel/tools/testing/selftests/bpf/prog_tests/sockmap_basic.c:604:13: error: too few arguments to function ‘create_pair’
    604 |         if (create_pair(AF_VSOCK, SOCK_STREAM, &conn, &peer))
        |             ^~~~~~~~~~~
  /home/runner/work/libbpf/libbpf/.kernel/tools/testing/selftests/bpf/prog_tests/sockmap_helpers.h:315:19: note: declared here
    315 | static inline int create_pair(int s, int family, int sotype, int *c, int *p)
        |                   ^~~~~~~~~~~
  /home/runner/work/libbpf/libbpf/.kernel/tools/testing/selftests/bpf/prog_tests/sockmap_basic.c:609:16: error: implicit declaration of function ‘bpf_program__attach_sockmap’; did you mean ‘bpf_program__attach_tcx’? [-Werror=implicit-function-declaration]
    609 |         link = bpf_program__attach_sockmap(prog, map);
        |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
        |                bpf_program__attach_tcx
  /home/runner/work/libbpf/libbpf/.kernel/tools/testing/selftests/bpf/prog_tests/sockmap_basic.c:609:14: error: assignment to ‘struct bpf_link *’ from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
    609 |         link = bpf_program__attach_sockmap(prog, map);
        |              ^

Signed-off-by: Shung-Hsi Yu <shung-hsi.yu@suse.com>