Fix BPF selftests compilation error on SLE15-SP{6,7} due to use of __arch_x86_64
Currently BPF selftests fail to compile with the following error:

  progs/verifier_sdiv.c:774:1: error: unknown type name '__arch_x86_64'
    774 | __arch_x86_64
        | ^
  progs/verifier_sdiv.c:775:10: error: expected parameter declarator
    775 | __xlated("0: r2 = 0x8000000000000000")
        |          ^
  progs/verifier_sdiv.c:775:10: error: expected ')'
  progs/verifier_sdiv.c:775:9: note: to match this '('
    775 | __xlated("0: r2 = 0x8000000000000000")
        |         ^
  progs/verifier_sdiv.c:776:1: error: expected function body after function declarator
    776 | __xlated("2: r3 = -1")
        | ^
  4 errors generated.

Signed-off-by: Shung-Hsi Yu <shung-hsi.yu@suse.com>