Drop "bpf: track changes_pkt_data property for global functions" series
They had been merged since v6.6.90, thus no longer needed. Having them
actually lead to error compiling BPF selftest

  progs/verifier_sock.c:1037:6: error: redefinition of 'skb_pull_data2'
   1037 | long skb_pull_data2(struct __sk_buff *sk, __u32 len)
        |      ^
  progs/verifier_sock.c:988:6: note: previous definition is here
    988 | long skb_pull_data2(struct __sk_buff *sk, __u32 len)
        |      ^
  progs/verifier_sock.c:1043:6: error: redefinition of 'skb_pull_data1'
   1043 | long skb_pull_data1(struct __sk_buff *sk, __u32 len)
        |      ^
  progs/verifier_sock.c:994:6: note: previous definition is here
    994 | long skb_pull_data1(struct __sk_buff *sk, __u32 len)
        |      ^
  progs/verifier_sock.c:1053:5: error: redefinition of 'invalidate_pkt_pointers_from_global_func'
   1053 | int invalidate_pkt_pointers_from_global_func(struct __sk_buff *sk)
        |     ^
  progs/verifier_sock.c:1004:5: note: previous definition is here
   1004 | int invalidate_pkt_pointers_from_global_func(struct __sk_buff *sk)
        |     ^
  3 errors generated.

Signed-off-by: Shung-Hsi Yu <shung-hsi.yu@suse.com>